<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>KappiMod</AssemblyName>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x64</Platforms>
    <OutputPath>bin\$(Configuration)\$(Loader)\</OutputPath>
    <IntermediateOutputPath>obj\$(Platform)\$(Configuration)\$(Loader)\</IntermediateOutputPath>
  </PropertyGroup>

  <Target Name="ValidateLoader" BeforeTargets="PrepareForBuild" Condition="'$(Loader)'!='ML' and '$(Loader)'!='BIE'">
    <Error Text="Invalid Loader '$(Loader)'. Use -p:Loader=ML or -p:Loader=BIE." />
  </Target>

  <!--Loaders-->
  <PropertyGroup Condition="'$(Loader)'=='ML'">
    <DefineConstants>$(DefineConstants);ML</DefineConstants>
    <AssemblyName>KappiMod.MelonLoader</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Loader)'=='BIE'">
    <DefineConstants>$(DefineConstants);BIE</DefineConstants>
    <AssemblyName>KappiMod.BepInEx</AssemblyName>
  </PropertyGroup>
  <!---->

  <!--References-->
  <ItemGroup Condition="'$(Loader)'=='ML'">
    <Content Include="$(ProjectDir)Assemblies\*">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Reference Include="$(ProjectDir)Assemblies\Loaders\MelonLoader\*.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ProjectDir)Assemblies\UserLibs\UniverseLib.ML.IL2CPP.Interop.dll" >
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Loader)'=='BIE'">
    <Content Include="$(ProjectDir)Assemblies\*">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Reference Include="$(ProjectDir)Assemblies\Loaders\BepInEx\*.dll" Exclude="$(ProjectDir)Assemblies\Loaders\BepInEx\dobby.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ProjectDir)Assemblies\UserLibs\UniverseLib.BIE.IL2CPP.Interop.dll" >
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <!---->
  
</Project>
